/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ContributionTrackerInterface extends Interface {
  getFunction(
    nameOrSignature: "getPoints" | "points" | "reportContribution"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ContributionReported"): EventFragment;

  encodeFunctionData(
    functionFragment: "getPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "points", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "reportContribution",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getPoints", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "points", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportContribution",
    data: BytesLike
  ): Result;
}

export namespace ContributionReportedEvent {
  export type InputTuple = [contributor: AddressLike, points: BigNumberish];
  export type OutputTuple = [contributor: string, points: bigint];
  export interface OutputObject {
    contributor: string;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContributionTracker extends BaseContract {
  connect(runner?: ContractRunner | null): ContributionTracker;
  waitForDeployment(): Promise<this>;

  interface: ContributionTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPoints: TypedContractMethod<[contributor: AddressLike], [bigint], "view">;

  points: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  reportContribution: TypedContractMethod<
    [contributor: AddressLike, contribPoints: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPoints"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "points"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "reportContribution"
  ): TypedContractMethod<
    [contributor: AddressLike, contribPoints: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContributionReported"
  ): TypedContractEvent<
    ContributionReportedEvent.InputTuple,
    ContributionReportedEvent.OutputTuple,
    ContributionReportedEvent.OutputObject
  >;

  filters: {
    "ContributionReported(address,uint256)": TypedContractEvent<
      ContributionReportedEvent.InputTuple,
      ContributionReportedEvent.OutputTuple,
      ContributionReportedEvent.OutputObject
    >;
    ContributionReported: TypedContractEvent<
      ContributionReportedEvent.InputTuple,
      ContributionReportedEvent.OutputTuple,
      ContributionReportedEvent.OutputObject
    >;
  };
}
